### ISSUE TITLE
Typo in I.rst

### ISSUE THREAD

**Issue by gesslar** [tsathoqqua/limadocs#3]
Dunno if this is done in-game or on the repo, but [https://github.com/tsathoqqua/limadocs/blob/main/docs/source/command/I.rst](I command) has a typo.

> "The use of **thes** command allows you to let other wizards know about any changes or additions that you made to the mud."

**Comment by tsathoqqua** [comment]
```
//: COMMAND
//$$ see: didlog
// USAGE
//       ``I <string>``
//
// This command produces the "did" log when you first log on.
// The use of this command allows you to let other wizards
// know about any changes or additions that you made to the mud.
//
//     ``I started adding help files for some wiz cmds``
//
// When logging in next time you (and other wizards) will see:
//
// Wed Apr 3 17:48:49 2024: Asmerian started adding help files for some wiz cmds
//
// .. TAGS: RST
```

Fixed, it's inline documentation for commands. Thanks for reporting!

**Comment by tsathoqqua** [comment]
Rolled to RTD
