### ISSUE TITLE
ReadTheDocs project private or not published?

### ISSUE THREAD

**Issue by LazyWizard** [tsathoqqua/limadocs#4]
There are various links to https://limadocs.readthedocs.io/, but that appears to be defunct. I can see it used to exist on archive.org, but it was either taken down or made private at some point. Was that intentional?

In the meantime I published https://limadocs-mirror.readthedocs.io/ for my own use (or anyone else who stumbles across this). Let me know if you want me to take the mirror down.

**Comment by tsathoqqua** [comment]
Sorry, the URL has been moved to:
https://limamudlib.readthedocs.io/

Where do you see references to https://limadocs.readthedocs.io/ ?

**Comment by LazyWizard** [comment]
Huh, I can't find the link I used now that I'm looking for it. It might have been an external tutorial linking to the old site.

The link to the documentation in [fluffos/lima's readme](https://github.com/fluffos/lima) also gives a "page not found" error (though the one in this repository is fixed), which might be why I didn't notice I had the wrong site. Sorry for the false report!

**Comment by tsathoqqua** [comment]
Yeah, sorry, fluffos/lima is rather old and outdated. I'm considering moving main repository to somewhere else. I just cannot pull things to fluffos/lima without a LOT of red tape. Thanks for your report anyways. Any help is appreciated - these kinds of resurrection projects for old software feels a lonely battle! :)
