### ISSUE TITLE
Should this be worded differently?

### ISSUE THREAD

**Issue by gesslar** [tsathoqqua/limadocs#5]
You say change the 1 to as low a number, but then recommend higher numbers. Do you mean something different here? Or do you mean fractional because you're using `call_out_walltime`?
https://github.com/tsathoqqua/limadocs/blob/1002dfa7addeda5ba6263c3d7bf3040e42487d14/docs/source/faq.rst?plain=1#L63

**Comment by tsathoqqua** [comment]
"Change the 1 here to a higher number that will make the issue go away. You can try
5 or 10, and then possibly reduce it a bit once the errors stop nagging you."

Simpler phrasing.
